import { useEffect, useMemo, useState } from "react";
import { apiRequest, uploadDocument } from "./api/client";
import type { Draft, Job, MaterialBatch, SearchTemplate, User } from "./types";
import "./styles.css";

type View = "jobs" | "profile" | "materials" | "settings" | "admin";

export default function App() {
  const [user, setUser] = useState<User | null>(null);
  const [booting, setBooting] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { apiRequest<User>("/api/auth/me").then(setUser).catch(() => setUser(null)).finally(() => setBooting(false)); }, []);
  if (booting) return <div className="boot-screen">加载工作台<span>·</span><span>·</span><span>·</span></div>;
  if (!user) return <AuthScreen onLogin={setUser} error={error} onError={setError} />;
  return <Workspace user={user} onLogout={() => setUser(null)} error={error} onError={setError} />;
}

function AuthScreen({ onLogin, onError, error }: { onLogin: (user: User) => void; onError: (message: string) => void; error: string }) {
  const [register, setRegister] = useState(false);
  const [form, setForm] = useState({ invite: "", username: "", password: "" });
  const update = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: value });
  const submit = async () => { try { const path = register ? "/api/auth/register" : "/api/auth/login"; const payload = register ? form : { username: form.username, password: form.password }; onLogin(await apiRequest<User>(path, { method: "POST", body: JSON.stringify(payload) })); } catch (err) { onError(err instanceof Error ? err.message : "登录失败"); } };
  return <main className="auth-page"><section className="auth-intro"><div className="brand-mark">JH<span>/</span>01</div><p className="eyebrow">PRIVATE JOB DESK</p><h1>把职位判断，<br /><em>留给你自己。</em></h1><p className="intro-copy">一个只面向邀请用户的求职工作台。职位共享，画像、评分和材料始终属于各自的账户。</p><div className="intro-stamp">BOSS 试点<br /><strong>LOCAL FIRST</strong></div></section><section className="auth-panel"><div className="panel-kicker">{register ? "加入工作台" : "欢迎回来"}</div><h2>{register ? "创建你的账户" : "进入职位工作台"}</h2><p className="muted">{register ? "使用管理员提供的一次性邀请码。" : "你的职位评分与材料不会与朋友混用。"}</p><div className="form-stack">{register && <label>邀请码<input value={form.invite} onChange={e => update("invite", e.target.value)} placeholder="粘贴一次性邀请码" /></label>}<label>用户名<input value={form.username} onChange={e => update("username", e.target.value)} placeholder="例如 chenyu" /></label><label>密码<input type="password" value={form.password} onChange={e => update("password", e.target.value)} placeholder="至少 8 位" /></label>{error && <div className="alert error">{error}</div>}<button className="primary-button" onClick={submit}>{register ? "创建账户" : "登录工作台"}<span>→</span></button></div><button className="text-button" onClick={() => setRegister(!register)}>{register ? "已有账户？返回登录" : "有邀请码？创建账户"}</button></section></main>;
}

function Workspace({ user, onLogout, onError, error }: { user: User; onLogout: () => void; onError: (message: string) => void; error: string }) {
  const [view, setView] = useState<View>("jobs"); const [notice, setNotice] = useState("");
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 3500); };
  const logout = async () => { await apiRequest("/api/auth/logout", { method: "POST" }); onLogout(); };
  return <div className="app-shell"><aside className="sidebar"><div className="brand-mark">JH<span>/</span>01</div><div className="side-label">求职工作台</div><nav><NavItem active={view === "jobs"} onClick={() => setView("jobs")} label="职位雷达" count="01" /><NavItem active={view === "profile"} onClick={() => setView("profile")} label="我的画像" count="02" /><NavItem active={view === "materials"} onClick={() => setView("materials")} label="材料审核" count="03" /><NavItem active={view === "settings"} onClick={() => setView("settings")} label="账户设置" count="04" />{user.role === "admin" && <NavItem active={view === "admin"} onClick={() => setView("admin")} label="管理员" count="AD" />}</nav><div className="sidebar-bottom"><div className="user-chip"><span className="avatar">{user.username.slice(0, 1).toUpperCase()}</span><span><strong>{user.username}</strong><small>{user.role === "admin" ? "管理员" : "邀请用户"}</small></span></div><button className="logout-button" onClick={logout}>退出账户</button></div></aside><main className="main-content">{notice && <div className="toast">{notice}</div>}{error && <div className="global-error">{error}</div>}{view === "jobs" && <JobsView notify={notify} onError={onError} onOpenMaterials={() => setView("materials")} />}{view === "profile" && <ProfileView notify={notify} onError={onError} />}{view === "materials" && <MaterialsView notify={notify} onError={onError} />}{view === "settings" && <SettingsView notify={notify} />}{view === "admin" && <AdminView notify={notify} onError={onError} />}</main></div>;
}
function NavItem({ active, onClick, label, count }: { active: boolean; onClick: () => void; label: string; count: string }) { return <button className={`nav-item ${active ? "active" : ""}`} onClick={onClick}><span>{label}</span><small>{count}</small></button>; }
function PageHeader({ eyebrow, title, subtitle, action }: { eyebrow: string; title: string; subtitle: string; action?: React.ReactNode }) { return <header className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-subtitle">{subtitle}</p></div>{action}</header>; }
function EmptyState({ title, copy, action }: { title: string; copy: string; action?: React.ReactNode }) { return <div className="empty-state"><span className="empty-line" /><h3>{title}</h3><p>{copy}</p>{action}</div>; }

function JobsView({ notify, onError, onOpenMaterials }: { notify: (message: string) => void; onError: (message: string) => void; onOpenMaterials: () => void }) {
  const [jobs, setJobs] = useState<Job[]>([]); const [templates, setTemplates] = useState<SearchTemplate[]>([]); const [templateId, setTemplateId] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [keyword, setKeyword] = useState("产品经理"); const [cities, setCities] = useState("丽水,杭州,金华"); const [collecting, setCollecting] = useState(false);
  const load = async () => { try { const [jobData, templateData] = await Promise.all([apiRequest<Job[]>("/api/jobs"), apiRequest<SearchTemplate[]>("/api/search-templates")]); setJobs(jobData); setTemplates(templateData); if (!templateId && templateData[0]) setTemplateId(templateData[0].id); } catch (err) { onError(err instanceof Error ? err.message : "职位加载失败"); } };
  useEffect(() => { load(); }, []);
  const selectedJobs = useMemo(() => jobs.filter(job => selected.includes(job.id)), [jobs, selected]);
  const createTemplate = async () => { try { const template = await apiRequest<SearchTemplate>("/api/search-templates", { method: "POST", body: JSON.stringify({ name: `${keyword}试点`, keywords: keyword.split(/[，, ]/).filter(Boolean), cities: cities.split(/[，,]/).map(v => v.trim()).filter(Boolean), hard_exclusions: ["劳务派遣", "外包"], weights: { keyword: 35, direction: 35, location: 20, salary: 10 } }) }); setTemplates([...templates, template]); setTemplateId(template.id); notify("搜索模板已保存"); } catch (err) { onError(err instanceof Error ? err.message : "模板保存失败"); } };
  const evaluate = async () => { if (!templateId || !selected.length) return; try { await apiRequest("/api/evaluations/batch", { method: "POST", body: JSON.stringify({ job_ids: selected, template_id: templateId }) }); await load(); notify("已完成私有评分"); } catch (err) { onError(err instanceof Error ? err.message : "评分失败"); } };
  const collect = async () => { if (!templateId) return; setCollecting(true); try { await apiRequest("/api/browser-sessions/start", { method: "POST" }); const task = await apiRequest<{ status: string; error_message?: string }>("/api/collection-tasks", { method: "POST", body: JSON.stringify({ template_id: templateId }) }); notify(task.status === "paused" ? task.error_message || "暂停人工处理" : "采集任务已启动"); await load(); } catch (err) { onError(err instanceof Error ? err.message : "采集任务启动失败"); } finally { setCollecting(false); } };
  const createBatch = async () => { if (!templateId || !selected.length) return; try { const batch = await apiRequest<{ id: string }>("/api/material-batches", { method: "POST", body: JSON.stringify({ job_ids: selected, template_id: templateId }) }); localStorage.setItem("job-hunter:last-batch", batch.id); notify(`已为 ${selectedJobs.length} 个职位生成草稿`); onOpenMaterials(); } catch (err) { onError(err instanceof Error ? err.message : "批量生成失败"); } };
  return <><PageHeader eyebrow="BOSS / POSITION RADAR" title="职位雷达" subtitle="共享职位池，私有判断层。先选职位，再生成材料。" action={<button className="outline-button" onClick={collect} disabled={collecting}>{collecting ? "启动中…" : "连接 BOSS 浏览器"}<span>↗</span></button>} /><section className="control-strip"><div><label>关键词<input value={keyword} onChange={e => setKeyword(e.target.value)} /></label></div><div><label>城市顺序<input value={cities} onChange={e => setCities(e.target.value)} /></label></div><div><label>当前模板<select value={templateId} onChange={e => setTemplateId(e.target.value)}><option value="">新建模板</option>{templates.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div><button className="small-button" onClick={createTemplate}>保存模板</button></section><div className="section-heading"><div><span className="section-number">01</span><h3>公共职位池</h3></div><span className="result-count">{jobs.length} 个职位 · 已选 {selected.length}</span></div>{!jobs.length ? <EmptyState title="还没有职位" copy="先连接 BOSS 浏览器完成一次只读采集。" action={<button className="primary-button compact" onClick={collect}>开始采集<span>→</span></button>} /> : <div className="job-list">{jobs.map(job => <JobCard key={job.id} job={job} checked={selected.includes(job.id)} onToggle={() => setSelected(selected.includes(job.id) ? selected.filter(id => id !== job.id) : [...selected, job.id])} />)}</div>}{selected.length > 0 && <div className="selection-bar"><strong>已选 {selected.length} 个职位</strong><span>批量操作只会写入你的私有空间</span><button className="secondary-button" onClick={evaluate}>更新评分</button><button className="primary-button compact" onClick={createBatch}>生成材料草稿<span>→</span></button></div>}</>;
}
function JobCard({ job, checked, onToggle }: { job: Job; checked: boolean; onToggle: () => void }) { const evaluation = job.evaluation; const salary = String(job.salary?.raw || (job.salary?.min ? `${job.salary.min}-${job.salary.max || ""}` : "薪资面议")); return <article className={`job-card ${checked ? "selected" : ""}`}><button className="check-box" aria-label={`选择 ${job.title}`} onClick={onToggle}>{checked ? "✓" : ""}</button><div className="tier-rail"><span>{job.location?.slice(0, 2) || "—"}</span></div><div className="job-main"><div className="job-topline"><span className="source-tag">{job.source}</span>{evaluation?.flags?.map(flag => <span className="risk-tag" key={flag}>{flag === "long_term_onsite" ? "长期驻场" : flag}</span>)}<span className="job-location">{job.location || "地点未标"}</span></div><h4>{job.title}</h4><p className="company">{job.company || "公司信息待补充"}</p><p className="job-description">{job.description || "暂无职位描述，建议打开原职位页面核对要求。"}</p></div><div className="job-score"><strong>{evaluation ? evaluation.score : "—"}</strong><small>{evaluation ? "私有评分" : "未评分"}</small><b>{salary}</b></div></article>; }

function ProfileView({ notify, onError }: { notify: (message: string) => void; onError: (message: string) => void }) {
  const [consent, setConsent] = useState(false); const [documents, setDocuments] = useState<{ document_id: string; filename: string }[]>([]); const [proposal, setProposal] = useState<{ id: string; data: Record<string, unknown>; source_refs: string[] } | null>(null); const [accepted, setAccepted] = useState<string[]>([]);
  useEffect(() => { apiRequest<{ enabled: boolean }>("/api/settings/ai-consent").then(data => setConsent(data.enabled)).catch(() => undefined); apiRequest<typeof documents>("/api/documents").then(setDocuments).catch(() => undefined); }, []);
  const toggle = async () => { try { const next = await apiRequest<{ enabled: boolean }>("/api/settings/ai-consent", { method: "POST", body: JSON.stringify({ enabled: !consent }) }); setConsent(next.enabled); notify(next.enabled ? "AI 资料处理已授权" : "AI 资料处理已关闭"); } catch (err) { onError(err instanceof Error ? err.message : "授权设置失败"); } };
  const upload = async (file?: File) => { if (!file) return; try { const document = await uploadDocument(file); setDocuments([...documents, document]); notify("资料已上传"); } catch (err) { onError(err instanceof Error ? err.message : "资料上传失败"); } };
  const propose = async () => { try { const data = await apiRequest<{ id: string; data: Record<string, unknown>; source_refs: string[] }>("/api/profile/proposals", { method: "POST", body: JSON.stringify({ document_ids: documents.map(document => document.document_id) }) }); setProposal(data); setAccepted(Object.keys(data.data || {})); } catch (err) { onError(err instanceof Error ? err.message : "画像提取失败"); } };
  const confirm = async () => { if (!proposal) return; try { await apiRequest(`/api/profile/proposals/${proposal.id}/confirm`, { method: "POST", body: JSON.stringify({ accepted_fields: accepted }) }); notify("画像已确认写入"); } catch (err) { onError(err instanceof Error ? err.message : "画像确认失败"); } };
  return <><PageHeader eyebrow="PROFILE / REVIEW FIRST" title="我的画像" subtitle="先上传资料，再逐项确认 AI 建议。未确认内容不会进入正式画像。" /><section className="profile-grid"><div className="profile-card"><div className="card-title"><span>01 / AI 处理授权</span><button className={`toggle ${consent ? "on" : ""}`} onClick={toggle}><i /></button></div><p>首次提取前需要明确同意。你可以随时关闭，关闭后不会发起新的模型调用。</p><div className={`consent-state ${consent ? "enabled" : ""}`}>{consent ? "已授权 · 可以提取" : "未授权 · AI 功能锁定"}</div></div><div className="profile-card upload-card"><div className="card-title"><span>02 / 原始资料</span><label className="upload-button">上传资料<input type="file" accept=".pdf,.docx,.md,.txt" onChange={e => upload(e.target.files?.[0])} /></label></div>{documents.length ? <ul className="document-list">{documents.map(doc => <li key={doc.document_id}><span className="file-type">{doc.filename.split(".").pop()?.toUpperCase()}</span>{doc.filename}<small>已保存在你的私有空间</small></li>)}</ul> : <div className="drop-hint">支持 PDF、DOCX、Markdown 和纯文本</div>}<button className="secondary-button" disabled={!consent || !documents.length} onClick={propose}>提取画像建议</button></div></section>{proposal && <section className="proposal-panel"><div className="section-heading"><div><span className="section-number">03</span><h3>逐项确认建议</h3></div><span className="result-count">来源：{proposal.source_refs.join("、")}</span></div><div className="proposal-fields">{Object.entries(proposal.data).map(([field, value]) => <label className="proposal-field" key={field}><input type="checkbox" checked={accepted.includes(field)} onChange={() => setAccepted(accepted.includes(field) ? accepted.filter(item => item !== field) : [...accepted, field])} /><span><b>{field}</b><small>{typeof value === "object" ? JSON.stringify(value) : String(value)}</small></span></label>)}</div><button className="primary-button" onClick={confirm}>确认选中内容<span>→</span></button></section>}</>;
}

function MaterialsView({ notify, onError }: { notify: (message: string) => void; onError: (message: string) => void }) {
  const [batchId, setBatchId] = useState(() => localStorage.getItem("job-hunter:last-batch") || ""); const [batch, setBatch] = useState<MaterialBatch | null>(null);
  const load = async () => { if (!batchId) return; try { setBatch(await apiRequest<MaterialBatch>(`/api/material-batches/${batchId}`)); } catch (err) { onError(err instanceof Error ? err.message : "批次加载失败"); } };
  useEffect(() => { if (batchId) load(); }, []);
  const review = async (draft: Draft, decision: string) => { try { await apiRequest(`/api/material-drafts/${draft.id}/review`, { method: "PATCH", body: JSON.stringify({ decision, notes: decision === "approved" ? "已人工核对" : "请重新检查职位匹配" }) }); notify(decision === "approved" ? "该岗位已通过审核" : "已标记为需要修改"); await load(); } catch (err) { onError(err instanceof Error ? err.message : "审核失败"); } };
  const finalize = async (draft: Draft) => { try { await apiRequest(`/api/material-drafts/${draft.id}/finalize`, { method: "POST" }); notify("DOCX/PDF 已生成"); await load(); } catch (err) { onError(err instanceof Error ? err.message : "文件生成失败"); } };
  return <><PageHeader eyebrow="MATERIALS / REVIEW GATE" title="材料审核" subtitle="每个岗位单独审核。审核通过后，才生成最终 DOCX/PDF。" action={<div className="batch-loader"><input placeholder="粘贴批次 ID" value={batchId} onChange={e => setBatchId(e.target.value)} /><button className="outline-button" onClick={load}>打开批次</button></div>} />{!batch ? <EmptyState title="等待材料批次" copy="从职位雷达中勾选多个职位并生成草稿，批次会出现在这里。" /> : <div className="draft-list">{batch.drafts.map((draft, index) => <article className="draft-card" key={draft.id}><div className="draft-index">0{index + 1}</div><div className="draft-content"><div className="draft-heading"><div><span className={`status-pill ${draft.status}`}>{draft.status === "draft_ready" ? "待审核" : draft.status}</span><h3>{draft.resume_text.split("\n")[0].replace("# ", "") || `岗位 ${draft.job_id}`}</h3></div><span className="draft-job-id">{draft.job_id}</span></div><div className="draft-preview"><div><small>简历草稿</small><p>{draft.resume_text.slice(0, 180)}...</p></div><div><small>求职信草稿</small><p>{draft.cover_letter_text.slice(0, 180)}...</p></div></div>{draft.status === "draft_ready" || draft.status === "changes_requested" ? <div className="draft-actions"><button className="secondary-button" onClick={() => review(draft, "changes_requested")}>要求修改</button><button className="primary-button compact" onClick={() => review(draft, "approved")}>审核通过<span>→</span></button></div> : draft.status === "approved" ? <button className="primary-button compact" onClick={() => finalize(draft)}>生成 DOCX/PDF<span>→</span></button> : draft.status === "finalized" ? <span className="finalized-label">最终文件已归档</span> : null}</div></article>)}</div>}</>;
}

function SettingsView({ notify }: { notify: (message: string) => void }) { return <><PageHeader eyebrow="ACCOUNT / PRIVATE BY DEFAULT" title="账户设置" subtitle="管理你的工作台状态。邮件找回暂未启用，由管理员手动重置密码。" /><section className="settings-card"><div><span className="setting-label">账户状态</span><strong>邀请制账户</strong></div><div><span className="setting-label">数据范围</span><strong>私有画像 · 私有评分 · 私有材料</strong></div><button className="secondary-button" onClick={() => notify("当前版本默认使用管理员提供的模型配置")}>查看模型配置</button></section></>; }
function AdminView({ notify, onError }: { notify: (message: string) => void; onError: (message: string) => void }) { const [invite, setInvite] = useState(""); const create = async () => { try { const result = await apiRequest<{ invite: string }>("/api/admin/invites", { method: "POST" }); setInvite(result.invite); notify("一次性邀请码已生成"); } catch (err) { onError(err instanceof Error ? err.message : "邀请码生成失败"); } }; return <><PageHeader eyebrow="ADMIN / INVITE ONLY" title="管理员" subtitle="只管理账户和邀请，不读取用户画像、职位评分或材料内容。" /><section className="admin-card"><div><span className="setting-label">一次性邀请码</span><strong>{invite || "尚未生成"}</strong></div><button className="primary-button compact" onClick={create}>生成邀请码<span>→</span></button></section></>; }
